### ISSUE TITLE
Runtime error : strip_headers and directus_refresh

### ISSUE THREAD

**Issue by timconsidine** [Slations/directus-php-sdk#6]
Using bare-bones test to create an item, following errors generated :

`PHP Warning:  Undefined array key "strip_headers" in Directus.php on line 28

PHP Warning:  Undefined array key "directus_refresh" in Directus.php on line 47`

**Comment by timconsidine** [comment]
The first undefined array error can be resolved by adding value to config :

  `$directus->config([
    "base_url" => "https://data.mytimeparty.uk/",
    "auth_storage" => "_SESSION", // set to _SESSION or _COOKIE
    "strip_headers" => false
  ]);`
 
Whether it should be true or false, I don't know yet.

The other error directus_refresh is still unresolved.

**Comment by Slations** [comment]
Thanks for letting me know about these issues, could i get a little more information on the hosting platform your using so I can try and recreate these issues for my self?

The first issue you've brought up regarding the strip_headers should be simple to solve and I will give it a go now, but to explain what it does it basically removes any headers from the Curl request if set to false you will have the data from Directus under data in the array and then under another value in that root array there will be headers and this will include all of the info from Curl. It's mainly used for debugging but can also be useful to people so I have left it in.

In regards to the directus_refresh I am working on getting that solved but can't give an exact update as of yet.

**Comment by timconsidine** [comment]
Thank you @Slations 
Understand now about strip_headers 👍 

My Directus9 instance is a packaged docker instance hosted on Linode running Cloudron (love 'em to bits).
My test script is just a barebones PHP script running locally on my Mac.
Not entirely sure if the test script is connecting correctly to the Directus9 app because it was barfing on these errors.  But this running the script runs to completion !
However no item created in Directus9 instance. I will debug more and let you know.

Test script :

        <?php 
        require 'Directus.php'; 
        $directus = new DirectusSDK();      
        $directus->auth_token('xxxxxx');        
        $directus->config([
          "base_url" => "https://xxx.yyyy.uk/",
          "auth_storage" => "_SESSION", 
          "strip_headers" => true
          ]);
        
        $playDate =  date('d/m/Y');
        
        $directus->create_items('test', array(
          "status" => "draft",
          "playerID" => "1234",
          "date_created" => $playDate,
          "value1" => 6,
          "value2" => 9
        ));
        
        echo 'Finished' .PHP_EOL;
        ?>

**Comment by timconsidine** [comment]
FYI 
Adjusted test script to read some data
It reaches the instance but says no permissions.  So checking those.  
Just letting you know that after resolving strip_headers, your Class may be working fine.

**Comment by timconsidine** [comment]
Update FYI.
Sorted permissions issue (stupid error on my side).
Can now read via API the sample data inserted in Directus9 table manually through admin login to the app.
Yay 👍 

**==> The directus_refresh array key error is not being reported anymore.**

However $directus->create_items is not creating items.
No errors returned.

**Comment by timconsidine** [comment]
**==> $directus->create_items DOES work fine**
Stupid camelCase error on my side.

So I have closed the issue.
Although I am interested if there is a way to get success message from API on creating or updating an item.

**MANY THANKS** for creating this API, and keeping it super simple.
I know I should learn some other languages, but PHP is my competency, and Directus9 forums don't seem interested in assisting with PHP interactions.

**Comment by Slations** [comment]
I'm glad you've got this all sorted. As much as I love PHP I also hate it hahaha.

Although new developments in my company are being done through Node.js we still have a lot of customers on Directus 8 with a PHP frontend so I needed a quick way to transfer them to v9. I'm just glad you've found what I have created so far useful as well. :)
