### ISSUE TITLE
PHP warning : search and filter

### ISSUE THREAD

**Issue by timconsidine** [Slations/directus-php-sdk#7]
Tried the README example of **Read By Query** for my table
Results are returned, but I get these warnings :

    Warning: Use of undefined constant search - assumed 'search' (this will throw an Error in a future version of PHP)
    Warning: Use of undefined constant filter - assumed 'filter' (this will throw an Error in a future version of PHP)

I have PHP v7.3.24 in my Mac terminal
Am I doing something wrong ?

**Comment by Slations** [comment]
Would you be ok sending over the code you are using? The filters and search should be effectively an array being passed directly to Directus with JSON Encode in the middle so I'm not 100% sure what could be causing this off the top of my head.

**Comment by timconsidine** [comment]
Code I am using is :

        <?php 
        require 'Directus.php'; 
        $directus = new DirectusSDK(); 
        $directus->auth_token('xxxx');
        $directus->config([
          "base_url" => "https://xxx.yyy.uk/",
          "auth_storage" => "_SESSION", 
          "strip_headers" => true
          ]);

        // this works fine
        $items = $directus->get_items('test');
        showitems($items);
        
        // this works fine
        $item = $directus->get_items('test', 2);
        print_r($item);        
        
        // this works but generates PHP warning
        $items = $directus->get_items('test', array(
          search => "1",
          filter => array(
            "date_created" => array(
              "_gte" => "\$NOW" // If you use Directus provided dynamic options like $NOW make sure you ascape the item \$NOW so PHP knows it's not a PHP variable
            )
          )
        ));
        showitems($items);
        
        function showitems($items) {
            foreach( $items['data'] as $item) {
                echo $item['id'] .' : '. $item['status'] .' : '. $item['date_created'] .' : '. $item['playerid'] .' : '. $item['value1'] .' : '. $item['value2'] .PHP_EOL;
            }
        }

        ?>

Hope this helps, and apologies if it is my code error

**Comment by Slations** [comment]
Thanks for sending that through, can you try wrapping the search and filter keys and see if that makes any difference as I think PHP has deprecated array keys being unwrapped, so from:

```
$items = $directus->get_items('test', array(
    search => "1",
    filter => array(
        "date_created" => array(
            "_gte" => "\$NOW" // If you use Directus provided dynamic options like $NOW make sure you ascape the item \$NOW so PHP knows it's not a PHP variable
        )
    )
));
```

to

```
$items = $directus->get_items('test', array(
    "search" => "1",
    "filter" => array(
        "date_created" => array(
            "_gte" => "\$NOW" // If you use Directus provided dynamic options like $NOW make sure you ascape the item \$NOW so PHP knows it's not a PHP variable
        )
    )
));
```

**Comment by timconsidine** [comment]
Thank you @Slations 
That did it, no PHP warnings on device running PHP 7.3.
I did test also on a device running PHP 8 and got a load of errors/warnings.
Will look into that further at some point, but for now this is solved.
Many thanks for your support.

**Comment by Slations** [comment]
My pleasure :)
